### ISSUE TITLE
broken update with pulp 2.12

### ISSUE THREAD

**Issue by cristifalcas** [theforeman/puppet-pulp#197]
With pulp 2.12 it's not possible to update the database anymore if workers and resource manager are running.

Is there any solution for this? It's safe to stop those services before managedb and start them again after?

**Comment by ehelms** [comment]
This should be safe. We stop services before we run managedb in the katello-installer upgrade steps.

**Comment by ekohl** [comment]
In a stand alone situation this is a problem and I'm not sure how to solve this. I think we're forced to use an exec for this.

**Comment by ekohl** [comment]
In an acceptance test I have the following workaround:
```puppet
exec { 'stop services':
  command     => '/bin/systemctl stop pulp_celerybeat pulp_workers pulp_resource_manager pulp_streamer && rm /var/lib/pulp/init.flag',
  subscribe   => Class['pulp::install'],
  before      => Class['pulp::database'],
  refreshonly => true,
}
```

This is not a nice workaround, but it works and is idempotent.
