### ISSUE TITLE
Provide a fact pulp_version

### ISSUE THREAD

**Issue by rgarrigue** [theforeman/puppet-pulp#235]
Hello

Is it possible to add a fact pulp_version, like you do for mongodb_version ? 

By the way, mongodb's module already expose a mongodb_version fact, making yours a bit redundant.

Best regards,

**Comment by ekohl** [comment]
That redundant fact was removed in https://github.com/Katello/puppet-pulp/pull/232.

Other than that I'm wondering what you'd need the pulp_version fact for.

**Comment by rgarrigue** [comment]
We've an itop cmdb, I'm working on a script to get informations from
puppetdb to push them into itop. Informations like "Software Pulp X.Y.Z on
this server".

2017-04-27 16:23 GMT+02:00 Ewoud Kohl van Wijngaarden <
notifications@github.com>:

**Comment by alexjfisher** [comment]
Are you interested in what pulp version a pulp *server* is running, or also what version consumers/agents are running?

**Comment by rgarrigue** [comment]
I'm interested in pup-server version

2017-04-28 14:42 GMT+02:00 Alex Fisher <notifications@github.com>:

**Comment by ekohl** [comment]
I'd love a PR to add this fact. At the moment I'm too busy with other matters to write & test this myself.

**Comment by ekohl** [comment]
This module is really in a maintenance-only mode now. Pulp 2 doesn't really receive any updates anymore and Pulp 3 uses a completely different module. That's why I'm closing this now.
