### ISSUE TITLE
pulp::version parameter needs to be split from plugins

### ISSUE THREAD

**Issue by rgarrigue** [theforeman/puppet-pulp#236]
Hello

There's an issue with this parameter. To illustrate, here's a piece of install.pp

```
class pulp::install {
  package { ['pulp-server', 'pulp-selinux', 'python-pulp-streamer']: ensure => $pulp::version, }
....
  if $pulp::enable_docker {
    package { ['pulp-docker-plugins']: ensure => $pulp::version, }
  }
```

And what's currently installed on my server

```
[root@content01 ~]# yum list installed | grep pulp
...
pulp-docker-plugins.noarch           2.3.0-1.el7                 @pulp-2-stable 
...
pulp-server.noarch                   2.12.1-1.el7                @pulp-2-stable 
```

RPM versions aren't synchronized. I tried to use pulp::version = 2.12.1-1.el7 and boom :

```
Error: Could not update: Failed to update to version 2.12.1-1.el7, got version 2.3.0-1.el7 instead
Error: /Stage[main]/Pulp::Install/Package[pulp-docker-plugins]/ensure: change from 2.3.0-1.el7 to 2.12.1-1.el7 failed: Could not update: Failed to update to version 2.12.1-1.el7, got version 2.3.0-1.el7 instead
```

That's not a major issue for me. I'm just enforcing version number all over our puppet stuff, for exemple to make sure we don't have different java version across servers just because we installed them one week appart ;-)

Best regards,

**Comment by ekohl** [comment]
This module is really in a maintenance-only mode now. Pulp 2 doesn't really receive any updates anymore and Pulp 3 uses a completely different module. That's why I'm closing this now.
