### ISSUE TITLE
parameter log_type is not honored

### ISSUE THREAD

**Issue by lambda123** [theforeman/puppet-pulp#379]
Hi,

parameter log_type is not usable with a different value from 'syslog'.

I've test and validate the update, not sure how to provide the patch, could you help me on that point.

Regards,

**Comment by ekohl** [comment]
Looks like cf1b633322625f3aba2191fdac3bec3aef4321c3 added it to `params.pp` but failed to add it to `init.pp` as an actual parameter. A patch for this would be welcome.

**Comment by lambda123** [comment]
Actually, just one line to add, what's the next point, I did not succed pushing my branch onto github, how do I have to proceed ?

**Comment by ekohl** [comment]
That should be sufficient.

Note that only `syslog` and `console` are valid. What are you exactly looking for?

**Comment by lambda123** [comment]
Just add line : 
Enum['console', 'syslog'] $log_type = $pulp::params::log_type,
before the log_level line

**Comment by lambda123** [comment]
in init.pp
