### ISSUE TITLE
deb repo provider

### ISSUE THREAD

**Issue by cbehlmer** [theforeman/puppet-pulp#392]
Hi,

is there a plan to implement a provider for debian based repositorys like rpm? 
Regards,

**Comment by ekohl** [comment]
AFAIK nobody is planning to, but there's no reason not to include it so PR's are welcome.

**Comment by ekohl** [comment]
This module is really in a maintenance-only mode now. Pulp 2 doesn't really receive any updates anymore and Pulp 3 uses a completely different module. That's why I'm closing this now.
